In [4]:
import tensorflow as tf

print(tf.__version__)

entero = tf.Variable(5, tf.int32)
puntoflotante = tf.Variable(4.989787328, tf.float32)

#vector
cadena = tf.string_join(["Me", "llamo", "Bartolo"])
vectorEnteros = tf.Variable([1,2,3,4,5], tf.int16)

# matrices al menos 2 dimesiones
matrizEnteros = tf.Variable([[7,5,4],[1,2,3]], tf.int32)
matrizfoat = tf.Variable([[1.1,1.2,1.3],[1.1,1.2,1.3]], tf.int32)
matrizString = tf.Variable([["Hola", "me", "llamo"],["pepe","el", "programaor"]], tf.string)



version
1.15.2


In [24]:
import tensorflow as tf

# entero
enteroVector = tf.constant([1,2,3,4,5])
matriz = tf.constant([[7,5,4],[1,2,3]])
matrizcadenas = tf.constant([ ["Hola", "me", "llamo", "el", "programador"] ], tf.string)

with tf.Session() as s:
    print(s.run(enteroVector))
    print(s.run(matriz))
    print(s.run(matrizcadenas))

[1 2 3 4 5]
[[7 5 4]
 [1 2 3]]
[[b'Hola' b'me' b'llamo' b'el' b'programador']]
